apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config-pvc
  labels:
    app: esphome
  namespace: iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-hostpath-esphome