apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome-deployment
  namespace: iot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        network-type: host
      hostNetwork: true
      containers:
        - name: esphome
          image: ghcr.io/esphome/esphome:2025.12.0
          ports:
            - name: http
              containerPort: 6052
          volumeMounts:
            - name: esphome-config-storage
              mountPath: /config
      volumes:
        - name: esphome-config-storage
          persistentVolumeClaim:
            claimName: esphome-config-longhorn-pvc
