apiVersion: v1
kind: Secret
metadata:
    name: strava-statistics-sensitive-config
stringData:
    config-personal.yaml: ENC[AES256_GCM,data:JaU0ALEDbusAftwvJbJcrdqWiEa7mHiYNfZi7IKy8kOkCbnE1Y5fgxiYsZ2pvvwSzcv3gfAeOi+zInWX0lG5W4Ibxay1v621FBXusmZKbEXrgkpk49wTL89cuG3TnE4XqUINGvi9drC43ue9H/+WAchOmY6C+wLdncMi8f1ZfazpY9XfooC4oId77lkZKenE3TeLpXOBwTb+wfnT0xCdCSx+djifXDzx58qkrleAJu2Vc2rE751LnvfYTY0JlgFdkCd3dHqN/Xht89Dw08uOa4yIAdAgBdJFB1bWSRgrhGVn8sgEvQVM1CJ2fQzVWop3SgNncXRI5s2gLI8WYIHRFx51zcP53s0j9GFYDHm6p2FHmolxgQnXHfXWCZtikVqhS0lOfKu2Qqfz8tqVAox9luWfzKTuDyeUpPVuiOwGzgC6B2Vq6nNdTLC3MbBTn4NtHcH2Qn7g4tIs63rxoAVj9uCL0kFhYF8IjddfbZXHQOqZ1vCz1oqROLVIeAg1xCKML3vfGlo45zvhJyuiM+OV46ITQwMPA0WT7iqb5+n5LTYFQJhu6UlZn5I35Ncu0wSvaIUBBjeCvSbc5gzZvQ+G7Wn5LPJezDJgjiOfqrq2JHj6wcP5HBxgK4AGM4za0C0ds4uO9kaO/drRARlCJD5niM3zJ1gRR1AXTe41Pzo0BNB1ojRmIk6l0O4CufqoqEKSBrLPU7RZy3CaGYMfcSPHK/1i2KSpYgzDLe0rdmMoHMb0oOe+GwTo+8guT1mBwh5CDUnUNo69Pa3L40LKkB5xQugHhtH2mfnyTVbl0alANEsk2Goua8W87RNrMQLiRDQ97kgfUQ1KEMJSPwuxMC3ySUXc0IuH1BGBuT3GDxYutXGyr5/ma+F2J6f9AgTqPX2H5//+m0jZW7P8m0AjfTQ6TFGrlnDKEoCSd0KbrmmGy7cFBz5V8IEPF1DnypiPtZzVD7fC7NFFhQKWVTyv1VDxQFhhxdZrfRz9nHbJj2wmCNQc9suygkm6CeiBS4iUywhkBeaxdRcdkPsYOU8aZiLlME7ptgtfXIWFV57gKDBGk1g=,iv:hXJj470vcaRUin5RJUe+Pk2y25wP38A/yEr/ht3ayBQ=,tag:xzgZBCKEvlcRw+ZF8ctFuQ==,type:str]
    config-ai.yaml: ENC[AES256_GCM,data:T1hes97EyRVL8Op6LipCgfGd8WsZk7et0Dv/Zc3Cd0W+2IJ29UV5tymcZRf/JmuHmC6pI55lkor2n4hVlqBz/lzb6iG4bNI5YJNx/OFZ2fbrV7g41VCjqPT98bo=,iv:I64hORZ8UgohH2Lu9Q63AwgIt8sQvPhoG1yPVXpOB/U=,tag:2qqbt4fDPM8VvrPuOyOSLQ==,type:str]
sops:
    age:
        - recipient: age1lyzn603kztevglyzhxxj6fcz4cptkvrt86yy7nul420w9f0kngtsnhmkln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SGg0RE5aajBiNjhYS1Ix
            cHZRY0pvcVFTdklyTDYrWnJnSERXZFdua1JNCmxNYVllNU9qaTduQXBVRmRkQnk0
            dlU3K2RaRmUyK000MS9JOXEyT0twNncKLS0tIG9wdm5RdU1jTEwzZitnUkc5amZ4
            bXkvSVpuencyQ1NTRWNlR1U1SUN5SmsKM/njYcHByzB5Kj4/Q7PuZ8OScoF/eFA2
            ukk1anuEKVJZcgDODypR1FxKX+TsAgJ65/SBaOd5k8eNL/bPxronSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T14:08:56Z"
    mac: ENC[AES256_GCM,data:5wZj/+5JaU+pwseySPDjApzERCHQYeNuWyw6F9UmiEQJ8BdP8V+wVf5j6VO1wfuyJ4lN1mc2R5FZNnb98Ltw2bzwk3Co8DhmKpHQOx2gKUlRRBbgxP2S91GqBukyI9CV5VKhEqyuStuUhKAtmewxlLmauZT1ej7UZcD4bTTlUNo=,iv:jfHhXGdYY31M0XByEOEQ+YVJb2vczscNW//Fs/o5a2w=,tag:S/i2hNa0sPyk84H1KCmXwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
