apiVersion: v1
kind: Secret
metadata:
    name: strava-statistics-sensitive-config
stringData:
    config-personal.yaml: ENC[AES256_GCM,data:004Dxu+2UTN9Enh3Ma41XAUj41M8F21mf3LqLZp1w+CnJThw+/Qvedow8lTWQ5n+mTZaSp4J6duT7sQr1DQZvKFjjCJbqx4mnOB4+lIfIfynyBvREDGaeL/xPTk7uyBZFcjVa3pawyQOyaXx9OgzjsW3ZrTTpCkV0HhiG7VoBUy5zeIfhquMvkWGSCA1TSSbbjDHA9xSbQ+HhgdAVk9hM7B023gQ2DgFdSRjgHwdJekHizt63Yiay60skiZjex9nERcNZJe1/UmPSZRGLZFgDsHoy70AqgHEmMPJ4WwkKn5Vrou7U9hK3x1sC0zslJi8bvqJrpvwGyTIrw7MSGlDkdZWPq7A+thLXg+H/oWXhlvY+0Icut7nEckdhE/+9mXSzzC9W124YrbXUSHX/7AB3Riz502nK3x0K9SmN3KBfSoUxzSe5J3mCt/tzj/iXTsAYEvu95Ykh1tAFzRvMg29ecGQWg+3x3soSs9jgZZ14rFN0x1BC1FFGl8pqAqG2Nl4jF8/oeyxFwX3j3dKsaFPZkkRfvhPRyN1lY7z+SMAvvlnC6NpBQJzpdP0F+1JQaCFBoBF1a5bynDdvgdJeMZP03MZHjzRYsozlRE1IL/WYBkJNYj+WnIlz575tPclP/BW/gTn9sOPZUr9i0cSzFMQSvzEGNv0H5TNF2Sl7cj3IMPpriEqUa0B0Cqv5+OISpL9MX/vIJWQE+iL+TGW+pyOrOIVu//Eq+WsGReyJDlIbPbSUffQ6tTajrhnSDGWvu06fKhikmAYsbyK3AdXF7B1K8wHkEkabnMC1SnW03cJ/0AOWr6rnPjHsJsuVNtNT4pn/68ydvT/VPdbXgtTnwajUcTkCgdpH6M/3u4JchU0yqlBtOkpcGzqcC6+wUEVoe7JknwYdGDKkNkxEeFuE/3bzNfvXwYviuRevDOlCL17+C9dmEFw8H9AB4+26w/+GZx+drybNwRdEcabQRzOk50jI4arXPCAKNzQOPvOzWZ2wgVbqA+QqNN7v+tv6QY99gv3oYkOU7wvDoBorS+3LE9cEO0hMup03bK0Lz+5UNmO9ao=,iv:cBmKvM5vPK0Eg3wB4WkVyQbwuBt8Uja8JGWOnoTjfJc=,tag:awXR/NsBefE5vSG5FZoHXA==,type:str]
    config-ai.yaml: ENC[AES256_GCM,data:ToBd3NjajLPuyJpNNxoTooYeB1htA6kkj3T4hdME11joP97rHdIKcW8P/xB0Nr7BX2/hLPGAoQuvX7c/a6C59FtEKK08jQC7oMqGYB+ZLdDGEuFgmZmzQDX9QYz00E73rn2Ff5fJPJM7HYUWgpUPvk+ko/xosd7bhlIO6kOkh3OdO4SxotfPdWoCZATqOy3T/of27hHc7hS8mSRK1RSUE8b1hqpK0+Zntn+d6DgF+q73wldKbpulTQ==,iv:Hb+chhSKhWw5811h86+eRsVIOl7yfZzVpWG7VG43Uzc=,tag:TzZJytPwUft049lx5Cyf6A==,type:str]
sops:
    age:
        - recipient: age1lyzn603kztevglyzhxxj6fcz4cptkvrt86yy7nul420w9f0kngtsnhmkln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteE9pekw3NS9CdDdhOGZp
            SHZZeUpQNlBUS2FNU2w0WmR2T2tJQk5UUVhVCnVCd2E0WGc4dnRRNG9Fb08wc2Jr
            dDU2U0dleEV0NUxpTVkzMHdCRmpGZ0EKLS0tIERVMEpPUmFlQnJDVC9TU2haQTBl
            Y1pzblE2My9ENWpBUjNiREhPbGM3dEUKf1HAwRSUny1VJIGv2A+nBPygah6jLfIT
            /BLR25+Ka58u+pUOCh/iltQrwYnBVngMYu/5Z4SZWdsk1LX6/HUp/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T05:44:45Z"
    mac: ENC[AES256_GCM,data:fabtiLJUqwXl7BFsgR09I0kleIjyl/VHu76ZgiA98j1tZo+l1ClaN/3ttNoafMFNUBwXQ3V/zEpCSbiCnZijcwXiFFgtyB3AhYz1Q/kw0Zo895lJxK98/a2DAX9JFJC4hFs1jUg2fgxj7JUhBmfX0pDhxK9t8QJWc+7qn9VC+X8=,iv:WrWQjOhFl+snWmryNPhfcvgDnRrRuuLOxWJjMf81c0w=,tag:XBFY8d0XHFpI5S9UONp83w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
