apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: strava-statistics
resources:
  - oauth-secret.enc.yaml
  - config-pvc.yaml
  - build-pvc.yaml
  - database-pvc.yaml
  - files-pvc.yaml
  - import-and-build-cronjob.yaml
  - deployment.yaml
  - httproute.yaml
  - service.yaml
configMapGenerator:
  - name: strava-statistics-config
    files:
      - app-config.yaml
