apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deployment
  namespace: iot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      nodeSelector:
        storage-type: hostpath
        network-type: host
      hostNetwork: true
      containers: 
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2025.11.3
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: home-assistant-config-storage
              mountPath: /config
      volumes:
        - name: home-assistant-config-storage
          persistentVolumeClaim:
            claimName: home-assistant-config-pvc