apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: esphome-httproute
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - esphome.travisprosser.ca
    - esphome-new.travisprosser.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: esphome
          port: 80
