apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: transmission
resources:
  - download-pvc.yaml
  - watch-pvc.yaml
  - config-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
