apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: lubelogger
resources:
  - data-pvc.yaml
  - protection-keys-pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
