apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment
  namespace: iot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      nodeSelector:
        storage-type: hostpath
      containers:
      - name: node-red
        image: nodered/node-red:4.1.2
        ports:
        - containerPort: 1880
        volumeMounts:
          - name: node-red-data-storage
            mountPath: /data
      volumes:
        - name: node-red-data-storage
          persistentVolumeClaim:
            claimName: node-red-data-pvc
