apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: global-https-redirect
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
      sectionName: web
  # No `hostnames` means it applies to ALL requests handled by the specified listener
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 302
