apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - repo.yaml
  - release.yaml
  - travisprosser-ca-wildcard-cert.yaml
  - travisprosser-com-wildcard-cert.yaml
  - global-https-redirect-httproute.yaml
  - dashboard-httproute.yaml
configMapGenerator:
  - name: traefik-helm-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
