apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: travisprosser-com-wildcard
  namespace: default
spec:
  secretName: travisprosser-com-tls
  dnsNames:
    - "travisprosser.com"
    - "*.travisprosser.com"
  issuerRef:
    name: letsencrypt-cloudflare-cluster-issuer
    kind: ClusterIssuer
