apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: travisprosser-ca-wildcard
  namespace: default
spec:
  secretName: travisprosser-ca-tls
  dnsNames:
    - "travisprosser.ca"
    - "*.travisprosser.ca"
  issuerRef:
    name: letsencrypt-cloudflare-cluster-issuer
    kind: ClusterIssuer
