apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: iot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-data-volume
              mountPath: /mosquitto/data
            - name: mosquitto-log-volume
              mountPath: /mosquitto/log
            - name: mosquitto-config-volume
              mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-data-volume
          persistentVolumeClaim:
            claimName: mosquitto-data-longhorn-pvc
        - name: mosquitto-config-volume
          configMap:
            name: mosquitto-configmap
        - name: mosquitto-log-volume
          emptyDir: {}
