apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mosquitto-config-configmap.yaml
  - mosquitto-deployment.yaml
  - mosquitto-ingress.yaml
  - mosquitto-pvc.yaml
  - mosquitto-service.yaml
