apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appconfig-pvc.yaml
  - media-pvc.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - values.yaml # for helm chart
      - config.yaml # application config
configurations:
  - kustomizeconfig.yaml
