apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
resources:
  - frigate-helmrelease.yaml
  - frigate-config-pvc.yaml
  - frigate-media-pvc.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - values.yaml # for helm chart
      - config.yaml # application config
    options:
      disableNameSuffixHash: true
