apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: frigate
resources:
  - appconfig-pvc.yaml
  - media-pvc.yaml
  - repo.yaml
  - release.yaml
  - httproute.yaml
configMapGenerator:
  - name: frigate-chart-values
    files:
      - values.yaml # for helm chart
configurations:
  - kustomizeconfig.yaml
