apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-namespace.yaml
  - cloudflared-namespace.yaml
  - csi-driver-nfs-namespace.yaml
  - longhorn-namespace.yaml
  - ./longhorn/
  - ./csi-driver-nfs/
  - ./cloudflared/
  - ./cert-manager/
