apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
resources:
  - ./namespace.yaml
  - ./camera-secret.enc.yaml
  - ./esphome/
  - ./frigate/
  - ./home-assistant/
  - ./mosquitto/
  - ./node-red/
  - ./zwave-js-ui/
  - ./amcrest2mqtt/
configMapGenerator:
  - name: camera-configs
    envs:
      - camera.env
