apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
resources:
  - ./esphome/
  - ./frigate/
  - ./home-assistant/
  - ./mosquitto/
  - ./node-red/
  - ./zwave-js-ui/
  - ./namespace.yaml
