apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        network-type: host
      hostNetwork: true
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2026.1.1
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: home-assistant-config-pvc
              mountPath: /config
        # Sidecar container for easier editing of
        - name: code-server
          image: lscr.io/linuxserver/code-server:4.108.0
          volumeMounts:
            - name: home-assistant-code-server-config-pvc
              mountPath: /config
            - name: home-assistant-config-pvc
              mountPath: /config/workspace/home-assistant/config
          ports:
            - containerPort: 8443
          env:
            - name: PGID
              value: "1000"  # Allows write-access to the files owned by home assistant
      volumes:
        - name: home-assistant-config-pvc
          persistentVolumeClaim:
            claimName: home-assistant-config
        - name: home-assistant-code-server-config-pvc
          persistentVolumeClaim:
            claimName: home-assistant-code-server-config
