apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: iot
spec:
  ingressClassName: traefik
  rules:
  - host: home-assistant.home-server-k3s.lan
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: home-assistant-service
            port: 
              number: 8123
