apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: home-assistant
resources:
  - pvc.yaml
  - code-server-pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - code-server-httproute.yaml
