apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant-deployment.yaml
  - home-assistant-ingress.yaml
  - home-assistant-pvc.yaml
  - home-assistant-service.yaml
