apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwave-js-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        zwave: "true"
      containers:
        - name: zwave-js-ui
          image: zwavejs/zwave-js-ui:11.9.1
          ports:
            - name: http
              containerPort: 8091
            - name: websocket
              containerPort: 3000
          volumeMounts:
            - name: zwave-js-ui-config-storage
              mountPath: /usr/src/app/store
      volumes:
        - name: zwave-js-ui-config-storage
          persistentVolumeClaim:
            claimName: zwave-js-ui-config
