apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: iot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      nodeSelector:
        storage-type: hostpath
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.21
        ports:
        - containerPort: 1883
        volumeMounts:
          - name: mosquitto-data-volume
            mountPath: /mosquitto/data
          - name: mosquitto-log-volume
            mountPath: /mosquitto/log
          - name: mosquitto-config-volume
            mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-data-volume
          persistentVolumeClaim:
            claimName: mosquitto-data-pvc
        - name: mosquitto-config-volume
          configMap:
            name: mosquitto-configmap
        - name: mosquitto-log-volume
          emptyDir: {}